In [1]:
import cv2
import numpy as np
import math
from keras.models import load_model

Using TensorFlow backend.


In [2]:
def input_image():
    file = input("Enter the path:")
    image_original = cv2.imread(file,1)
    return image_original

In [3]:
def standardazie(image):
    image_mean = np.mean(image)
    image_std  = np.std(image)
    standardized_image = (image - image_mean) / image_std
    return standardized_image

In [4]:
def pre_processing(image):
    grey_image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    resized_image = cv2.resize(grey_image, (28,28), interpolation = cv2.INTER_AREA)
    reshaped_image = resized_image.reshape(28, 28, 1)
    ret,threshold = cv2.threshold(reshaped_image,127,255,cv2.THRESH_BINARY)
    threshold = threshold - 255
    standardized_threshold = standardazie(threshold)
    blur_image = cv2.GaussianBlur(standardized_threshold,(5,5),0)
    preprocessed_image = blur_image.reshape(1,28,28,1)
    return preprocessed_image

In [5]:
def main():
    #"/Users/akshayrajeev/Documents/Computer Vision/cs512-f20-akshay-r/AS3/data/odd.png"
    #"/Users/akshayrajeev/Documents/Computer Vision/cs512-f20-akshay-r/AS3/data/even.jpg"  
    global image_original 
    global display_preprocessed_image
    global loaded_model
    global preprocessed_image
    global classes
    
    image_original = input_image()
    cv2.imshow ('Original_image', image_original)
    cv2.waitKey()
    
    preprocessed_image = pre_processing(image_original)
    display_preprocessed_image = preprocessed_image.reshape(28,28,1)
    print(display_preprocessed_image)
    cv2.imshow ('Preprocessed_image', display_preprocessed_image)
    cv2.waitKey()
    
    loaded_model = load_model('Basic_odd_or_even.h5')
    classes = loaded_model.predict(preprocessed_image, batch_size=10)
    print(classes)
    
#     if(classes == 1):
#         print("The inupt image is an odd number!")
#     else:
#         print("The input image is an even number!")    

In [6]:
main()

Enter the path:/Users/akshayrajeev/Documents/Computer Vision/cs512-f20-akshay-r/AS3/data/even.jpg
[[[-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]]

 [[-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.43950972]
  [-0.3977531 ]
  [-0.33511817]
  [-0.30380071]
  [-0.33511817]
  [-0.3977531 ]
  [-0.43950972]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]
  [-0.44994887]]

 [

[[0.8988393  0.10116071]]
